version: '3.8'

services:
  sql-qa-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URI=sqlite:///./data/chinook_qa.db
      - LOG_LEVEL=INFO
      - ENABLE_CHAIN_APPROACH=true
      - ENABLE_AGENT_APPROACH=true
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - sql-qa-network

networks:
  sql-qa-network:
    driver: bridge
